[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"

[window.padding]
x = 3
y = 0
