# frozen_string_literal: true

cask_args appdir: '/Applications'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'shiwano/formulas'

brew 'zsh'
brew 'zsh-completions'
brew 'git'
brew 'reattach-to-user-namespace'
brew 'ctags'
brew 'cmake'
brew 'tmux'
brew 'coreutils'
brew 'wget'
brew 'tree'
brew 'ack'
brew 'mcrypt'
brew 'jpeg'
brew 'pstree'
brew 'gnu-sed'
brew 'curl'
brew 'openssl'
brew 'libxml2'
brew 'lv'
brew 'nkf'
brew 'mercurial'
brew 'watch'
brew 'nmap'
# brew 'musta'
# brew 'misakura'
brew 'multitail'
brew 'iproute2mac'
brew 'clang-format'
brew 'mingw-w64'
brew 'neovim'
brew 'libimobiledevice'
brew 'ideviceinstaller'
brew 'ios-deploy'
brew 'stern'
brew 'mas'
brew 'ghq'
brew 'yarn'
brew 'libidn'
brew 'awscli'
brew 'amazon-ecs-cli'
brew 'graphviz'
brew 'bazelisk'
brew 'golangci-lint'
brew 'docker-slim'
brew 'fzf'
brew 'ripgrep'
brew 'bat'
brew 'git-lfs'
brew 'asdf'
brew 'java'
brew 'plantuml'
brew 'gh'
brew 'openapi-generator'
brew 'stripe/stripe-cli/stripe'
brew 'git-delta'

cask 'alfred'
cask 'google-chrome'
cask 'firefox'
cask 'appcleaner'
cask 'dropbox'
cask 'skype'
cask 'keepassxc'
cask 'growlnotify'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'webpquicklook'
cask 'libreoffice'
cask 'steam'
cask 'licecap'
cask 'gyazo'
cask 'spectacle'
cask 'android-sdk'
cask 'android-platform-tools'
cask 'slack'
cask 'google-japanese-ime'
cask 'docker'
cask 'karabiner-elements'
cask 'font-sauce-code-pro-nerd-font'
cask 'ngrok'
cask 'kindle'
cask 'zoom'
cask 'deepl'
cask 'google-cloud-sdk'
cask 'tableplus'
cask 'discord'
cask 'android-studio'
cask 'microsoft-edge-dev'
cask 'imageoptim'
cask 'neovide'
cask 'wireshark'
cask 'ghostty'

mas 'The Unarchiver', id: 425_424_353
mas 'LINE', id: 539_883_307
