return {
  { "rc", "~/.config/nvim/init.lua" },
  { "tag", "~/.config/nvim/lua/bookmarks.lua" },
  { "zsh", "~/.zshrc" },
  { "zshlocal", "~/.zshrc.local" },
  { "git", "~/.gitconfig" },
  { "gitignore", "~/.gitignore" },
  { "tmux", "~/.tmux.conf" },
  { "tmuxdarwin", "~/.tmux.darwin.conf" },
  { "homebrew", "~/dotfiles/Brewfile" },
  { "asdf", "~/.tool-versions" },
  { "ghostty", "~/.config/ghostty/config" },
  { "go", "~/.config/nvim/after/ftplugin/go.vim" },
  { "dart", "~/.config/nvim/after/ftplugin/dart.vim" },
  { "lua", "~/.config/nvim/after/ftplugin/lua.vim" },
  { "cs", "~/.config/nvim/after/ftplugin/cs.vim" },
  { "cpp", "~/.config/nvim/after/ftplugin/cpp.vim" },
  { "markdown", "~/.config/nvim/after/ftplugin/markdown.vim" },
  { "sh", "~/.config/nvim/after/ftplugin/sh.vim" },
  { "coc", "~/.config/nvim/coc-settings.json" },
}
