return {
  { "rc", "~/.config/nvim/init.lua" },
  { "tag", "~/.config/nvim/lua/bookmarks.lua" },
  { "zsh", "~/.zshrc" },
  { "zshlocal", "~/.zshrc.local" },
  { "git", "~/.gitconfig" },
  { "gitignore", "~/.gitignore" },
  { "tmux", "~/.tmux.conf" },
  { "tmuxdarwin", "~/.tmux.darwin.conf" },
  { "homebrew", "~/dotfiles/Brewfile" },
  { "asdf", "~/.tool-versions" },
  { "ghostty", "~/.config/ghostty/config" },
  { "coc", "~/.config/nvim/coc-settings.json" },
  { "go", "~/.config/nvim/after/ftplugin/go.lua" },
  { "gomod", "~/.config/nvim/after/ftplugin/gomod.lua" },
  { "dart", "~/.config/nvim/after/ftplugin/dart.lua" },
  { "lua", "~/.config/nvim/after/ftplugin/lua.lua" },
  { "cs", "~/.config/nvim/after/ftplugin/cs.lua" },
  { "cpp", "~/.config/nvim/after/ftplugin/cpp.lua" },
  { "markdown", "~/.config/nvim/after/ftplugin/markdown.lua" },
  { "sh", "~/.config/nvim/after/ftplugin/sh.lua" },
  { "shaderlab", "~/.config/nvim/after/ftplugin/shaderlab.lua" },
  { "nginx", "~/.config/nvim/after/ftplugin/nginx.lua" },
}
