return {
  { name = "rc", path = "~/.config/nvim/init.lua" },
  { name = "tag", path = "~/.config/nvim/lua/bookmarks.lua" },
  { name = "zsh", path = "~/.zshrc" },
  { name = "zshlocal", path = "~/.zshrc.local" },
  { name = "git", path = "~/.gitconfig" },
  { name = "gitignore", path = "~/.gitignore" },
  { name = "tmux", path = "~/.tmux.conf" },
  { name = "tmuxdarwin", path = "~/.tmux.darwin.conf" },
  { name = "homebrew", path = "~/dotfiles/Brewfile" },
  { name = "asdf", path = "~/.tool-versions" },
  { name = "ghostty", path = "~/.config/ghostty/config" },
  { name = "coc", path = "~/.config/nvim/coc-settings.json" },
  { name = "go", path = "~/.config/nvim/after/ftplugin/go.lua" },
  { name = "gomod", path = "~/.config/nvim/after/ftplugin/gomod.lua" },
  { name = "dart", path = "~/.config/nvim/after/ftplugin/dart.lua" },
  { name = "lua", path = "~/.config/nvim/after/ftplugin/lua.lua" },
  { name = "cs", path = "~/.config/nvim/after/ftplugin/cs.lua" },
  { name = "cpp", path = "~/.config/nvim/after/ftplugin/cpp.lua" },
  { name = "markdown", path = "~/.config/nvim/after/ftplugin/markdown.lua" },
  { name = "sh", path = "~/.config/nvim/after/ftplugin/sh.lua" },
  { name = "shaderlab", path = "~/.config/nvim/after/ftplugin/shaderlab.lua" },
  { name = "nginx", path = "~/.config/nvim/after/ftplugin/nginx.lua" },
}
